config/routes.rb
Projekt::Application.routes.draw do
  get "home/index"

  resources :posts
  resources :friendlists
  
  match 'index' => 'home#index', :as => :index
 
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation
  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]


  def new
    @user = User.new

    @post = Post.new
    @friendlist = Friendlist.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end

  end

  def show
    @profil = User.find(params[:id])
    @id = params[:id]
    @posts = Post.where(:id_owner => @id)
    @author = User.find(@id)
    @my_friendlist = Friendlist.where(:id_friend == @profil.id || :id_user == @profil.id)

    @add_friend = Friendlist.new 
    @post = Post.new    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end

  def delete
    Post.delete(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def author(poster)
    @author = User.find(poster)     
    @author.username
  end

  def friend_finder(friendlist, id)
    friends_list = []

    #usunac te w ktorych uzytkownik nie bierze udzialu
    friendlist.reject! {|friend| friend.id_user.to_i != id.to_i && 
friend.id_friend.to_i != id.to_i  }    

    friendlist.each do |friend|
     # frieds list whithout us 
     (friend.id_user.to_i != id.to_i) ? (friends_list << friend.id_user) : (friends_list << friend.id_friend)
    end

    friends_list.uniq! 
    User.where(:id => friends_list)
  end

end

app/views/users/.#show.html.erb
metrox@metrox@home.1403:1310144302

app/views/users/_add_friend.html.erb
<%= form_for @add_friend do |f| %>
    <%= hidden_field_tag(:id_friend, @profil.id) %>
    <%= hidden_field_tag(:id_user, current_user.id) %>
    <%= submit_tag 'Add to friends' %>
<% end %>

app/views/users/_add_to_friend.html.erb
<%= form_for Friendlist.new do |f| %>
    <%= hidden_field_tag(:id_friend, @profil.id) %>
    <%= submit_tag "Add to friend" %>
<% end %>

app/views/users/_comment.html.erb
<%= form_for @post do |f| %>
    <%= hidden_field_tag(:id_owner, @profil.id) %>
    <%= f.text_area :comment %><br />

    <%= submit_tag "Comment" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/add_friend.html.erb
  <div class="field">
    <%= @friendlist.label :id_user %><br />
    <%= f.text_field :id_user %>
  </div>
  <div class="field">
    <%= f.label :id_friend %><br />
    <%= f.text_field :id_friend %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/users/comment.html.erb
  <div class="field">
    <%= @post.label :id_sender %><br />
    <%= f.text_field :id_sender %>
  </div>
  <div class="field">
    <%= f.label :id_owner %><br />
    <%= f.text_field :id_owner %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="profil_name">
Profil uzytkownika: <%= @profil.username %><br />
</div>

Witaj panie: <%= current_user.username %><br />
<div class="main">
  <% @posts.each do |post| %>
    <tr>
      <div class="author">
        <td>
          <%= author(post.id_sender) %>    
          <% if (current_user.id == post.id_owner) or (current_user.id == post.id_sender) %>
            <div class="destroy">
              <%= link_to 'Destroy', post, :method => :delete, :confirm => 'Are you sure?' %>

            </div>
          <% end %>
       </td>
     </div>
   
     <div class="comment">
       <td>
        <%= post.comment %>
       </td>
     </div>
   </tr>
  <% end %>
  <div class="komcie">
    <%= render 'comment' %>
  </div>
</div>

<div class="friends">
  Znajomi<br />
  
   <!-- lista znajomych -->
   <% friends_profil = '0' %>
   <% friends = friend_finder(@my_friendlist, @profil.id) %>
   <% friends.each do |friend| %>
     <br /> <!-- link do profilu -->
    <%= link_to "#{friend.username}", user_path(friend.id) %>
     <% if friend.username == current_user.username %>
        <% friends_profil = '1' %>
     <% end %>
   <% end %>
</div>

   <!-- Dodawanie do znajomych -->
  
  <% if (friends_profil == '0') && (@profil.id != current_user.id) %>
   <div class="add_friend">
     <%= render 'add_friend' %>
   </div>
  <% end %>