config/routes.rb
Projekt::Application.routes.draw do
  get "home/index"

  resources :posts
  resources :friendlists
  
  match 'index' => 'home#index', :as => :index
 
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users

  root :to => "home#index"

end

app/models/friendlist.rb
class Friendlist < ActiveRecord::Base
  validates_presence_of :id_user
  validates_presence_of :id_friend
end

app/controllers/friendlists_controller.rb
class FriendlistsController < ApplicationController
  # GET /friendlists
  # GET /friendlists.xml
  def index
    @friendlists = Friendlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @friendlists }
    end
  end

  # GET /friendlists/1
  # GET /friendlists/1.xml
  def show
    @friendlist = Friendlist.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @friendlist }
    end
  end

  # GET /friendlists/new
  # GET /friendlists/new.xml
  def new
    @friendlist = Friendlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @friendlist }
    end
  end

  # GET /friendlists/1/edit
  def edit
    @friendlist = Friendlist.find(params[:id])
  end

  # POST /friendlists
  # POST /friendlists.xml
  def create
   @friendlist = Friendlist.new
   @friendlist[:id_user] = params[:id_user]
   @friendlist[:id_friend] = params[:id_friend]
  
    respond_to do |format|
      if @friendlist.save
        # format.html { redirect_to(@friendlist, :notice => 'Friendlist was successfully created.') }
        format.html { redirect_to(user_path(params[:id_friend])) }
        format.xml  { render :xml => @friendlist, :status => :created, :location => @friendlist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @friendlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friendlists/1
  # PUT /friendlists/1.xml
  def update
    @friendlist = Friendlist.find(params[:id])

    respond_to do |format|
      if @friendlist.update_attributes(params[:friendlist])
        format.html { redirect_to(@friendlist, :notice => 'Friendlist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @friendlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /friendlists/1
  # DELETE /friendlists/1.xml
  def destroy
    @friendlist = Friendlist.find(params[:id])
    @friendlist.destroy

    respond_to do |format|
      format.html { redirect_to(friendlists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/friendlists_helper.rb
module FriendlistsHelper
end

app/views/friendlists/_form.html.erb
<%= form_for(@friendlist) do |f| %>
  <% if @friendlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendlist.errors.count, "error") %> prohibited this friendlist from being saved:</h2>

      <ul>
      <% @friendlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 USER <%= params[:id_user] %><br />
 FRIEND <%= params[:id_friend] %>
  <div class="field">
    <%= f.label :id_user %><br />
    <%= f.text_field :id_user %>
  </div>
  <div class="field">
    <%= f.label :id_friend %><br />
    <%= f.text_field :id_friend %>
  </div>
  <div class="field">
    <%= f.label :user_approved %><br />
    <%= f.check_box :user_approved %>
  </div>
  <div class="field">
    <%= f.label :friend_approved %><br />
    <%= f.check_box :friend_approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendlists/edit.html.erb
<h1>Editing friendlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendlist %> |
<%= link_to 'Back', friendlists_path %>

app/views/friendlists/index.html.erb
<h1>Listing friendlists</h1>

<table>
  <tr>
    <th>Id user</th>
    <th>Id friend</th>
    <th>User approved</th>
    <th>Friend approved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendlists.each do |friendlist| %>
  <tr>
    <td><%= friendlist.id_user %></td>
    <td><%= friendlist.id_friend %></td>
    <td><%= friendlist.user_approved %></td>
    <td><%= friendlist.friend_approved %></td>
    <td><%= link_to 'Show', friendlist %></td>
    <td><%= link_to 'Edit', edit_friendlist_path(friendlist) %></td>
    <td><%= link_to 'Destroy', friendlist, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendlist', new_friendlist_path %>

app/views/friendlists/new.html.erb
<h1>New friendlist</h1>

<%= render 'form' %>

<%= link_to 'Back', friendlists_path %>

app/views/friendlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id user:</b>
  <%= @friendlist.id_user %>
</p>

<p>
  <b>Id friend:</b>
  <%= @friendlist.id_friend %>
</p>

<p>
  <b>User approved:</b>
  <%= @friendlist.user_approved %>
</p>

<p>
  <b>Friend approved:</b>
  <%= @friendlist.friend_approved %>
</p>


<%= link_to 'Edit', edit_friendlist_path(@friendlist) %> |
<%= link_to 'Back', friendlists_path %>